-   pattern: '/^.{6,}$/'
    message: 'Password length is minimum 5 character'

-   pattern: '/.*[0-9].*/'
    message: 'Password must contain at least one digit'

-   pattern: '/^(?:(.)(?!\1{2,}))*$/'
    message: 'Password must contain no more than two repeating characters'

-   pattern: "/(?=.*[A-Z])|(?=.*[.,:;'!@#$%^&*_+=|(){}[?\\-\\]\\/\\])(?!.*[<>`])/"
    message: 'Password must contain at least one uppercase character or one special character'
