App\Entity\Password:
    type:  entity
    table: passwords
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        password:
            type:     string
            length:   255
            column:   password
            nullable: false
        isValid:
            type:     boolean
            column:   valid
            nullable: false
